version: '3.8'
services:
  db:
    container_name: wb_orders
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: seleroad
      POSTGRES_PASSWORD: seleroad
      POSTGRES_DB: orders

    volumes:
      - ./database_postgres:/var/lib/postgresql/data
volumes:
  database_postgres:
